### ISSUE TITLE
dom object를 읽는 기능을 추가 가능 할까요?

### ISSUE THREAD

**Issue by CharlesKwonOhjun** [smok95/wv2#3]
수고 많으십니다. 
DOM Object를 읽어 getelementbyid와 같은 내부 method호출이 가능한 기능을 추가 하실 계획이 있으신지요?
지금 기능에 이 기능이 추가되면 참 좋을 듯 합니다. 감사합니다.

**Comment by smok95** [comment]
안녕하세요!
아래와 같은 식으로 스크립트를 사용할 수 있는데요
LPCWSTR script = L"document.getElementById(\"demo\").style.backgroundColor = \"green\";";
wv2executeScriptSync(handle, script);
// 또는 wv2executeScript(handle, script, nullptr);

이거보다 더 전문적으로 dom을 사용하고 싶으신건가요?

**Comment by CharlesKwonOhjun** [comment]
안녕하세요?  

네 맞습니다. 

oEdge.wv.document 처럼
wv object 아래로 DOM을 불러 온다면 최고의 프로젝이 될 듯 합니다!

새해 복 많이 받으세요.

**Comment by smok95** [comment]
네 감사합니다. 새해 복 많이 받으세요 ^^
아쉽지만 제가 시간도 부족한데 능력까지 부족해서 사실상 어려울 것 같네요 
혹시라도 .net쪽에 https://github.com/R2D221/WebView2.DOM 요런 프로젝트가 있는데
이거는 어떠실까요?
