### ISSUE TITLE
NewWindowRequested

### ISSUE THREAD

**Issue by Aut-Design** [smok95/wv2#4]
need add NewWindowRequested

**Comment by smok95** [comment]
Hello! It might take a while, but let me give it a shot.

**Comment by smok95** [comment]
> need add NewWindowRequested
Hello! It might take a while, but let me give it a shot.

**Comment by smok95** [comment]
@Aut-Design 
I have added support for the NewWindowRequested event. However, not all features are supported yet. Please refer to the example for more details

**Comment by Aut-Design** [comment]
ICoreWebView2DocumentTitleChangedEventHandler
ICoreWebView2WebResourceRequestedEventHandler
ICoreWebView2DOMContentLoadedEventHandler
ICoreWebView2DownloadStartingEventHandler
ICoreWebView2ScriptDialogOpeningEventHandler 
Hello! Need Add
