### ISSUE TITLE
wv2setSourceChangedEventHandler

### ISSUE THREAD

**Issue by Aut-Design** [smok95/wv2#7]
Need to add wv2setSourceChangedEventHandler
NavigationCompleted bool success, int webErrorStatus

**Comment by smok95** [comment]
I'm sorry, but I'm too busy at the moment, so it might be difficult for a while. I'll work on it as soon as I have time.

**Comment by smok95** [comment]
The navigationCompleted function signature has been updated.
Please refer to the example for usage details.

**Comment by Aut-Design** [comment]
thank you!
