### ISSUE TITLE
WebMessage Received cannot be triggered

### ISSUE THREAD

**Issue by Aut-Design** [smok95/wv2#8]
WebMessage Received cannot be triggered

**Comment by smok95** [comment]
![image](https://github.com/user-attachments/assets/aeed78d5-da1c-42b9-8ab7-d4b7e577a87e)

I added the WebMessageReceived event handling code to the example, and it's working without any issues, as shown in the captured screenshot.

What seems to be the problem?

**Comment by Aut-Design** [comment]
OK！
