### ISSUE TITLE
Configure WebView2 to persist Cookies

### ISSUE THREAD

**Issue by Aut-Design** [smok95/wv2#9]
Can I configure WebView2 to persist Cookies? Thanks
![Uploading 微信图片_20240911142409.png…]()

**Comment by Aut-Design** [comment]
https://learn.microsoft.com/zh-hk/microsoft-edge/webview2/reference/win32/icorewebview2cookie?view=webview2-1.0.2739.15

**Comment by smok95** [comment]
I added cookie-related features. Please refer to the example.

![image](https://github.com/user-attachments/assets/fac273b4-3be9-4a36-86c8-a4d488da3b30)

**Comment by Aut-Design** [comment]
good！thank you!
